apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app-teste
  name: app-teste
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xxnamexx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-teste
    spec:
      containers:
      - image: ghcr.io/nopp/app-teste:v0.0.2
        name: app-teste
        resources: {}
status: {}
