name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
  bimp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      id: version
      uses: anothrNick/github-tag-action@1.36.0
      env:
        WITH_V: true
        DRY_RUN: true
        VERBOSE: false
        PRERELEASE_SUFFIX: rc
        RELEASE_BRANCHES: master,main
    - run: echo ${{ steps.version.outputs.new_tag }}
