name: Sec

on:
  push:
    branches: [ "main" ]

jobs:
  semgrep:
      name: Scan
      runs-on: ubuntu-20.04
      container:
        image: returntocorp/semgrep
      steps:
      - uses: actions/checkout@v3
      - run: |-
          python3 -m pip install ansi2html        
          semgrep scan --config auto > opa 
          cat opa | ansi2html > semgrep.html
          ls -ltr
