name: Sec

on:
  push:
    branches: [ "main" ]

env:
  token: ${{ secrets.TOKEN }}
  
jobs:
  Sec:
      name: Scan
      runs-on: ubuntu-20.04
      container:
        image: shiftleft/scan
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
          with:
            repository: nopp/action-labs
            ref: main
            token: ${{ secrets.TOKEN }}
            path: ./action-labs
        - name: Scans
          uses: ./action-labs/workflows/
