name: Sec

on:
  push:
    branches: [ "main" ]

jobs:
  Sec:
      name: Scan
      runs-on: ubuntu-20.04
      container:
        image: returntocorp/semgrep
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
          with:
            repository: nopp/action-labs
            ref: main
            token: ${{ secrets.TOKEN }}
            path: ./action-labs
        - name: runs
          run: |- 
            ls -ltr
            ls -ltr ./.github/
        - name: Scans
          uses: ./action-labs/workflows/
